FROM hadoop-hive-spark-base

RUN sudo pip install -U pip &&\
    sudo pip install --no-cache-dir \
    pandas \
    openpyxl \
    findspark \
    tensorflow \
    tensorflow-io \
    tensorflow-serving-api
